baseURL: "https://lucasgiori.github.io"
languageCode: "en-us"
title: "lucasgiori.dev"
theme: ["PaperMod"]

params:
  author: "Lucas Giori Cesconetto"
  description: "Aqui eu falo sobre desenvolvimento de software"
  
  keywords: [ADR, Arquitetura de Software, PaperMod]
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false
  social: true

  profileMode:
    enabled: false # needs to be explicitly set
    title: lucasgiori.dev
    subtitle: "Engenharia de software"
    imageUrl: "<img location>"
    imageWidth: 120
    imageHeight: 120
    imageTitle: my image
    buttons:
      - name: Posts
        url: posts
      - name: Tags
        url: tags

    homeInfoParams:
      Title: "Hi there \U0001F44B"
      Content: Welcome to my blog

    socialIcons:
      - name: x
        url: "https://x.com/"
      - name: stackoverflow
        url: "https://stackoverflow.com"
      - name: github
        url: "https://github.com/"