name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Hugo Site
        run: |
          docker build -f Dockerfile.prod -t lucasgiori.dev .
          docker run --rm -v ${{ github.workspace }}:/src lucasgiori.dev hugo
      
      - name: Set permissions for public directory
        run: chmod -R 755 public
        
      - name: Create CNAME file in public directory
        run: |
          echo "lucasgiori.dev" > CNAME
          echo "www.lucasgiori.dev" >> CNAME
        working-directory: public  

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public