name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: "list"
        run: |
          ls -all

      - name: Build Hugo Site
        run: |
          docker build -f Dockerfile.prod -t lucasgiori.dev .
          docker run --rm -v ${{ github.workspace }}:/src -v ${{ github.workspace }}/CNAME:/src/public/CNAME lucasgiori.dev hugo
      
      - name: Show CNAME file
        run: |
          cat CNAME
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public